repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.2
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    exclude: ^.*\b(migrations)\b.*$

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
