export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS";
export const FETCH_PLAYLISTS_SUCCESS = "FETCH_PLAYLISTS_SUCCESS";
export const FETCH_PLAYLISTS_FAILURE = "FETCH_PLAYLISTS_FAILURE";

export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";
export const CREATE_PLAYLIST_FAILURE = "CREATE_PLAYLIST_FAILURE";

export const DELETE_PLAYLIST = "DELETE_PLAYLIST";
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const DELETE_PLAYLIST_FAILURE = "DELETE_PLAYLIST_FAILURE";

export const UPDATE_PLAYLIST = "DELETE_PLAYLIST";
export const UPDATE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const UPDATE_PLAYLIST_FAILURE = "DELETE_PLAYLIST_FAILURE";

export const SELECT_PLAYLIST = "SELECT_PLAYLIST";
export const SET_PLAYLISTS = "SET_PLAYLISTS";
